version: '3.11'

services:
  266_container:
    image: ebrown/nlp-gpu-jupyter:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - /home/rcao/repos_linux/:/tf/notebooks
    ports:
      - 6006:6006
      - 8888:8888
    stdin_open: true # docker run -i
    tty: true # docker run -t
